[package]
name = "silk-net"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy_matchbox = { workspace = true }
serde = "1.0"
bincode = "1.3"
